# Generated by Django 5.1.5 on 2025-07-23 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_status',
            field=models.CharField(choices=[('inactive', 'inactive'), ('active', 'active')], max_length=29),
        ),
        migrations.AlterField(
            model_name='customer',
            name='store_kind',
            field=models.CharField(choices=[('مصنع', 'مصنع'), ('تقديم خدمات', 'تقديم خدمات'), ('مطعم\\مقهى', 'مطعم\\مقهى'), ('متجر', 'متجر')], max_length=20),
        ),
        migrations.AlterField(
            model_name='menu',
            name='template',
            field=models.CharField(choices=[('template2', 'منتج'), ('template4', 'خدمة'), ('template1', 'طعام')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.menu')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.products')),
            ],
        ),
    ]
