# Generated by Django 5.1.5 on 2025-07-23 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_customer_customer_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='store_kind',
            field=models.CharField(choices=[('مطعم\\مقهى', 'مطعم\\مقهى'), ('تقديم خدمات', 'تقديم خدمات'), ('متجر', 'متجر'), ('مصنع', 'مصنع')], max_length=20),
        ),
        migrations.AlterField(
            model_name='menu',
            name='template',
            field=models.CharField(choices=[('template1', 'طعام'), ('template4', 'خدمة'), ('template2', 'منتج')], max_length=20, null=True),
        ),
    ]
