# Generated by Django 5.1.5 on 2025-07-23 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_customer_store_kind_alter_menu_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='desc',
            field=models.CharField(default='اهلا بكم في متجري المتواضع', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='store_kind',
            field=models.CharField(choices=[('متجر', 'متجر'), ('تقديم خدمات', 'تقديم خدمات'), ('مصنع', 'مصنع'), ('مطعم\\مقهى', 'مطعم\\مقهى')], max_length=20),
        ),
        migrations.AlterField(
            model_name='menu',
            name='template',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
