# Generated by Django 5.1.5 on 2025-07-27 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_menu_desc_alter_customer_store_kind_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='location_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='color',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='size',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='available_colors',
            field=models.CharField(blank=True, help_text='أدخل الألوان مفصولة بفاصلة مثل: أحمر, أخضر, أزرق', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='available_sizes',
            field=models.CharField(blank=True, help_text='أدخل المقاسات مفصولة بفاصلة مثل: S, M, L, XL', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_status',
            field=models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], max_length=29),
        ),
        migrations.AlterField(
            model_name='customer',
            name='store_kind',
            field=models.CharField(choices=[('مطعم\\مقهى', 'مطعم\\مقهى'), ('متجر', 'متجر'), ('غير ذلك', 'غير ذلك')], max_length=20),
        ),
    ]
