# Generated by Django 5.1.5 on 2025-07-27 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_customer_location_url_orderitem_color_orderitem_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_status',
            field=models.CharField(choices=[('inactive', 'inactive'), ('active', 'active')], max_length=29),
        ),
    ]
