# Generated by Django 5.1.5 on 2025-07-27 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_customer_customer_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cpdiscount',
            name='products',
        ),
        migrations.AlterField(
            model_name='customer',
            name='store_kind',
            field=models.CharField(choices=[('متجر', 'متجر'), ('غير ذلك', 'غير ذلك'), ('مطعم\\مقهى', 'مطعم\\مقهى')], max_length=20),
        ),
        migrations.AddField(
            model_name='cpdiscount',
            name='products',
            field=models.ManyToManyField(related_name='discounts', to='core.products'),
        ),
    ]
