# Generated by Django 5.1.5 on 2025-07-27 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_cpdiscount_products_alter_customer_store_kind_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cpdiscount',
            name='customer',
        ),
        migrations.AddField(
            model_name='cpdiscount',
            name='menu',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='core.menu'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_status',
            field=models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], max_length=29),
        ),
        migrations.AlterField(
            model_name='customer',
            name='store_kind',
            field=models.CharField(choices=[('متجر', 'متجر'), ('مطعم\\مقهى', 'مطعم\\مقهى'), ('غير ذلك', 'غير ذلك')], max_length=20),
        ),
    ]
