# Generated by Django 5.1.5 on 2025-07-27 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_cpdiscount_customer_cpdiscount_menu_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='delivery',
        ),
        migrations.AddField(
            model_name='menu',
            name='recivieing',
            field=models.CharField(choices=[('التوصيل', 'التوصيل'), ('التوصيل او الاستلام في المحل', 'التوصيل اوالاستلام في المحل'), ('الاستلام في المحل', 'الاستلام في المحل')], default='التوصيل', max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_status',
            field=models.CharField(choices=[('inactive', 'inactive'), ('active', 'active')], max_length=29),
        ),
        migrations.AlterField(
            model_name='customer',
            name='store_kind',
            field=models.CharField(choices=[('مطعم\\مقهى', 'مطعم\\مقهى'), ('متجر', 'متجر'), ('غير ذلك', 'غير ذلك')], max_length=20),
        ),
    ]
