# Generated by Django 5.1.5 on 2025-08-27 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_menu_delivery_menu_recivieing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='ordernumber',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_status',
            field=models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], max_length=29),
        ),
        migrations.AlterField(
            model_name='customer',
            name='store_kind',
            field=models.CharField(choices=[('غير ذلك', 'غير ذلك'), ('مطعم\\مقهى', 'مطعم\\مقهى'), ('متجر', 'متجر')], max_length=20),
        ),
        migrations.AlterField(
            model_name='menu',
            name='recivieing',
            field=models.CharField(choices=[('التوصيل', 'التوصيل'), ('الاستلام في المحل', 'الاستلام في المحل'), ('التوصيل او الاستلام في المحل', 'التوصيل اوالاستلام في المحل')], default='التوصيل', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
