# Generated by Django 5.1.5 on 2025-08-30 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_order_order_type_order_ordernumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_status',
            field=models.CharField(choices=[('inactive', 'inactive'), ('active', 'active')], max_length=29),
        ),
        migrations.AlterField(
            model_name='customer',
            name='store_kind',
            field=models.CharField(choices=[('متجر', 'متجر'), ('مطعم\\مقهى', 'مطعم\\مقهى'), ('غير ذلك', 'غير ذلك')], max_length=20),
        ),
        migrations.AlterField(
            model_name='menu',
            name='recivieing',
            field=models.CharField(choices=[('الاستلام في المحل', 'التسليم فقط في المحل'), ('التوصيل', 'التوصيل فقط'), ('التوصيل او الاستلام في المحل', ' التوصيل و التسليم في المحل')], default='التوصيل', max_length=50),
        ),
    ]
