# Generated by Django 5.1.5 on 2025-09-01 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_customer_customer_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cpdiscount',
            name='products',
        ),
        migrations.AddField(
            model_name='cpdiscount',
            name='product',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='core.products'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='store_kind',
            field=models.CharField(choices=[('غير ذلك', 'غير ذلك'), ('مطعم\\مقهى', 'مطعم\\مقهى'), ('متجر', 'متجر')], max_length=20),
        ),
    ]
