# Generated by Django 5.1.5 on 2025-09-02 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_cpdiscount_products_cpdiscount_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpdiscount',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='core.products'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='recivieing',
            field=models.CharField(choices=[('التوصيل', 'التوصيل فقط'), ('الاستلام في المحل', 'التسليم فقط في المحل'), ('التوصيل او الاستلام في المحل', ' التوصيل و التسليم في المحل')], default='التوصيل', max_length=50),
        ),
    ]
