# Generated by Django 5.1.5 on 2025-09-02 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_cpdiscount_product_alter_menu_recivieing'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='is_free',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_status',
            field=models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], max_length=29),
        ),
        migrations.AlterField(
            model_name='customer',
            name='store_kind',
            field=models.CharField(choices=[('غير ذلك', 'غير ذلك'), ('متجر', 'متجر'), ('مطعم\\مقهى', 'مطعم\\مقهى')], max_length=20),
        ),
        migrations.AlterField(
            model_name='menu',
            name='recivieing',
            field=models.CharField(choices=[('التوصيل', 'التوصيل فقط'), ('التوصيل او الاستلام في المحل', ' التوصيل و التسليم في المحل'), ('الاستلام في المحل', 'التسليم فقط في المحل')], default='التوصيل', max_length=50),
        ),
    ]
