# Generated by Django 5.1.5 on 2025-09-02 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_subscription_is_free_alter_customer_customer_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='total_earned',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_status',
            field=models.CharField(choices=[('inactive', 'inactive'), ('active', 'active')], max_length=29),
        ),
        migrations.AlterField(
            model_name='customer',
            name='store_kind',
            field=models.CharField(choices=[('مطعم\\مقهى', 'مطعم\\مقهى'), ('غير ذلك', 'غير ذلك'), ('متجر', 'متجر')], max_length=20),
        ),
        migrations.AlterField(
            model_name='menu',
            name='recivieing',
            field=models.CharField(choices=[('التوصيل', 'التوصيل فقط'), ('الاستلام في المحل', 'التسليم فقط في المحل'), ('التوصيل او الاستلام في المحل', ' التوصيل و التسليم في المحل')], default='التوصيل', max_length=50),
        ),
    ]
