# Generated by Django 5.1.5 on 2025-09-03 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_coupon_total_earned_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminSales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='cpdiscount',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='cpdiscount',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='discount',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='discount',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='menu',
            name='recivieing',
            field=models.CharField(choices=[('التوصيل او الاستلام في المحل', ' التوصيل و التسليم في المحل'), ('الاستلام في المحل', 'التسليم فقط في المحل'), ('التوصيل', 'التوصيل فقط')], default='التوصيل', max_length=50),
        ),
    ]
