# Generated by Django 5.1.5 on 2025-09-03 10:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_adminsales_alter_cpdiscount_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminsales',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adminsales',
            name='profit',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_status',
            field=models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], max_length=29),
        ),
        migrations.AlterField(
            model_name='customer',
            name='store_kind',
            field=models.CharField(choices=[('غير ذلك', 'غير ذلك'), ('مطعم\\مقهى', 'مطعم\\مقهى'), ('متجر', 'متجر')], max_length=20),
        ),
    ]
